name: Build Syncer Image

permissions:
  packages: write

on:
  push:
    branches:
    - main
    - 'release-*'

jobs:
  syncer-image:
    name: Build Syncer Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: v1.17

      # Build and push a syncer image, tagged with the commit SHA and the branch name.
      - uses: imjasonh/setup-ko@v0.4
      - run: ko publish ./cmd/syncer -t $(git rev-parse --short "$GITHUB_SHA"),${{ github.ref_name }}
